name: tests

on:
  push:
    branches:
      - master
      - dev

  pull_request:
    branches: ['*']

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:

    - name: Install dependencies
      run: |
        sudo apt-get -y -qq update
        sudo apt-get -y install octave liboctave-dev

    - name: Clone spm_2_bids
      uses: actions/checkout@v3
      with:
        submodules: true
        fetch-depth: 2

    - name: get bids-matlab and JSONio
      run: |
        make install_dev_octave

    - name: MOxUnit Action
      uses: joergbrech/moxunit-action@v1.2.0
      with:
        tests: tests # files or directories containing the MOxUnit test cases
        src: src  # directories to be added to path before running the tests.
        ext: tests/utils lib/bids-matlab lib/JSONio # External resources to add to the search put (excluded from coverage)
        # data: # Directory for test data
        with_coverage: true
        cover_xml_file: coverage.xml

    - name: Code coverage
      uses: codecov/codecov-action@v1
      with:
       file:  coverage.xml # optional
       flags: unittests # optional
       name: codecov-umbrella # optional
       fail_ci_if_error: true # optional (default = false)
