name: tests

on:
  push:
    branches:
      - master
      - main
      - dev
  pull_request:
    branches: '*'

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:

    - name: Clone spm_2_bids         
      uses: actions/checkout@v2
      with:
        submodules: true
        fetch-depth: 2  
          
    - name: get bids-matlab
      run: |
        make install_dev

    - name: MOxUnit Action
      uses: joergbrech/moxunit-action@master
      with:
        tests: tests # files or directories containing the MOxUnit test cases
        src: src lib  # directories to be added to the Octave search path before running the tests. 
        ext: tests/utils # External resources to add to the search put (excluded from coverage)
        # data: # Directory for test data  
        with_coverage: true
        cover_xml_file: coverage.xml

    - name: Upload coverage
      uses: actions/upload-artifact@v1 
      with: 
        name: coverage_file 
        path: coverage.xml         

    - name: Code coverage
      uses: codecov/codecov-action@v1
      with:
       file:  coverage.xml # optional
       flags: unittests # optional
       name: codecov-umbrella # optional
       fail_ci_if_error: true # optional (default = false)        



      

